### ISSUE TITLE
Muted role for every created channel

### ISSUE THREAD

**Issue by KnightLegionNetwork** [Cog-Creators/Red-Dashboard#62]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
The bot should add the muted role to every new created text channel in the discord with the messages permission negated.

**Describe alternatives you've considered**
[]

**Additional context**
[]

**Comment by Drapersniper** [comment]
I believe you wanted to use https://github.com/Cog-Creators/Red-DiscordBot/issues/new/choose which would create an issur on Red-Discordbot repo, rather than on the dashboard repo
