### ISSUE TITLE
Dashboard Update.

### ISSUE THREAD

**Issue by DairyWeb3638077** [Cog-Creators/Red-Dashboard#67]
Hello, I was wondering if you could make the dashboard like these other discord bot dashboards where you can change the prefix of the bot, manage the bot settings, manage channels like the welcome channel, mod log channel etc. or like whatever you can do to the bot via commands, you could do in the dashboard. Kinda like this
![image](https://user-images.githubusercontent.com/86208278/158319236-4f4e8399-c48f-4742-abb4-579f0f936381.png)

**Comment by NeuroAssassin** [comment]
Feature requests are not being accepted by banned users at this time.  Due to the alpha status of the current project, I ask that all feature requests be provided in my own Discord server, or the general Red server, and for Github issues to remain as bug tracking.
