### ISSUE TITLE
Unknown locale 'no_NO'

### ISSUE THREAD

**Issue by GameHackerTV** [Cog-Creators/Red-Dashboard#70]
### What part of dashboard are you having an issue with?

- [ ] Documentation
- [x] Dashboard webserver
- [ ] Dashboard cog

### What happened?

i can't start the webserver.
### What did you expect to happen?

I installed (probably) everything correctly, but the webserver gave an error.
![IMG_20220515_104504](https://user-images.githubusercontent.com/86518375/169084675-2815af2f-9131-4d35-b683-4e5a05588bdd.jpg)

### What can we do to reproduce this?

I just installed everything according to the docks.
### What is your bot/webserver running on?
- **Operating system**: Ubuntu/Linux
- **Python version**: 3.8
- **Dashboard webserver version**: 0.1.8a
- **Dashboard cog version**: Irrelevant (latest on 18.05.22)

### What are you having issues on?
- **Operating system**: Irrelevant
- **Browser**: Irrelevant

**Comment by Drapersniper** [comment]
Did you mean nb_NO?

**Comment by GameHackerTV** [comment]
> Did you mean nb_NO?

please check the screenshot
![IMG_20220515_104504](https://user-images.githubusercontent.com/86518375/169101205-48201caa-4d4b-4752-ba79-517d31513ba4.jpg)

**Comment by Kowlin** [comment]
``no_NO`` doesn't exist due to multiple locales and dialects existing within the country. The proper locale code is ``nb_NO``.

**Comment by GameHackerTV** [comment]
where can i change it?

**Comment by japandotorg** [comment]
Not sure but looks like you gotta change it from here https://github.com/Cog-Creators/Red-Dashboard/blob/05dedd3e54a036da66ce7bdd4b1284ccacc9fa68/reddash/app/base/templates/site_template/scripts-sidebar.html#L26

**Comment by GameHackerTV** [comment]
thanks, you can rename no_NO to nb_NO

**Comment by aikaterna** [comment]
I'm reopening this for tracking because we need to fix it ourselves, just because you've edited things on your copy doesn't mean it's fixed for everyone.

**Comment by c4p-n1ck** [comment]
@aikaterna where were you? dead? till this date while I was crying to fix it?

**Comment by aikaterna** [comment]
> @aikaterna where were you? dead? till this date while I was crying to fix it? Sending a PR soon.

Treat others with respect as you interact with issues or PRs on our repo. Watch your tone.

**Comment by psharma04** [comment]
> I'm reopening this for tracking because we need to fix it ourselves, just because you've edited things on your copy doesn't mean it's fixed for everyone.

I've opened a Pull Request (#72) to fix this issue :)
